[platformio]
default_envs = nano_old_bootloader

[env:nano_old_bootloader]
platform = atmelavr
framework = arduino
board = nanoatmega328

; Configure the Serial Monitor speed
monitor_speed = 115200

; Automatically open the serial monitor after a successful upload
targets = upload, monitor

; Pulls the standard HX711 library by bogde directly from the PIO registry
lib_deps =
    bogde/HX711 @ ^0.7.5